[#ftl]
[#-- @implicitly included --]
[[#-- @ftlvariable name="shiro" type="com.jagregory.shiro.freemarker.ShiroTags" --]]
[#--数据备份与恢复--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_DATA_BAK" type="java.lang.String" --]
[#--系统管理--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_SYSTEM" type="java.lang.String" --]
[#--测试404--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_CESHI404" type="java.lang.String" --]
[#--测试500--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_CESHI500" type="java.lang.String" --]
[#--操作日志--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_OPERATE" type="java.lang.String" --]
[#--菜单管理--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_MENU" type="java.lang.String" --]
[#--角色管理--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_ROLE" type="java.lang.String" --]
[#--文件管理--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_FILE" type="java.lang.String" --]
[#--档案中心--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_ARCHIVE" type="java.lang.String" --]
[#--运维管理--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_OPERATION" type="java.lang.String" --]
[#--数据库监控--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_DATA_MONITOR" type="java.lang.String" --]
[#--系统运行状态--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_SYSTEM_STATUS" type="java.lang.String" --]
[#--字典管理--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_DICT" type="java.lang.String" --]
[#--短信配置--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_SMS" type="java.lang.String" --]
[#--记事本--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_NOTEPAD" type="java.lang.String" --]
[#--图标管理--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_ICON" type="java.lang.String" --]
[#--Demo--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_DEMO" type="java.lang.String" --]
[#--未知菜单--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_UNKNOWN" type="java.lang.String" --]
[#--登录错误记录--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_LOGIN_RECORD" type="java.lang.String" --]
[#--用户管理--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_USER" type="java.lang.String" --]
[#--组织机构管理（旧）--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_ORG" type="java.lang.String" --]
[#--组织机构--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_ORG_NEW" type="java.lang.String" --]
[#--首页--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_HOME" type="java.lang.String" --]
[#--邮箱配置--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_MAIL" type="java.lang.String" --]
[#--删除用户--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_USER_DELETE" type="java.lang.String" --]
[#--保存用户--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_USER_SAVE" type="java.lang.String" --]
[#--保存角色--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_ROLE_SAVE" type="java.lang.String" --]
[#--删除角色--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_ROLE_DELETE" type="java.lang.String" --]
[#--分配角色--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_ROLE_ALLOT" type="java.lang.String" --]
[#--保存菜单--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_MENU_SAVE" type="java.lang.String" --]
[#--删除菜单--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_MENU_DELETE" type="java.lang.String" --]
[#--保存组织机构--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_ORG_SAVE" type="java.lang.String" --]
[#--删除组织机构--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_ORG_DELETE" type="java.lang.String" --]
[#--上传文件--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_FILE_UPLOAD" type="java.lang.String" --]
[#--删除文件--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_FILE_DELETE" type="java.lang.String" --]
[#--保存字典--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_DICT_SAVE" type="java.lang.String" --]
[#--删除字典--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_DICT_DELETE" type="java.lang.String" --]
[#--保存字典属性--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_DICT_ATTR_SAVE" type="java.lang.String" --]
[#--删除字典属性--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_DICT_ATTR_DELETE" type="java.lang.String" --]
[#--定义字典属性--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_DICT_ALLOT" type="java.lang.String" --]
[#--保存备份策略--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_DATA_BAK_STRATEGY_SAVE" type="java.lang.String" --]
[#--立即备份--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_DATA_BAK_SAVE" type="java.lang.String" --]
[#--删除备份--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_DATA_BAK_DELETE" type="java.lang.String" --]
[#--恢复备份--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_DATA_BAK_RECOVER" type="java.lang.String" --]
[#--系统通知-删除--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_MESSAGE_DELETE" type="java.lang.String" --]
[#--系统通知-设置已读--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_MESSAGE_SET_READ" type="java.lang.String" --]
[#--保存登录策略--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_LOGIN_STRATEGY_SAVE" type="java.lang.String" --]
[#--删除登录错误记录--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_LOGIN_RECORD_DELETE" type="java.lang.String" --]
[#--保存邮箱配置--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_MAIL_CONFIG_SAVE" type="java.lang.String" --]
