spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/${custom.database}?&autoReconnect=true
    username: postgres
    password: 123456

custom:
  # 是否开启http重定向到https
  redirect-https: false
  # 数据库是否docker环境
  dbIsDocker: false